btcsuite/btcrpcclient

.travis.yml, goclean.sh
Also update to use the new container-based builds
For now, golint has been disabled since it fails due to wanting HTTPPostMode.  This change will be made as a part of the upgrade to use btcjson2 since it involves an API change.
=> Update TravisCI to goclean script.

chain.go, doc.go, examples/bitcoincorehttp/main.go, extensions.go, goclean.sh, infrastructure.go, mining.go, net.go, notify.go, rawrequest.go, rawtransactions.go, wallet.go
Requires conformal/btcjson#34.
This pull request contains several changes needed to update the client to use the upcoming version 2 of btcjson.  In addition it contains a couple of other minor changes along the way.
While the underlying changes are quite large, the public API of this package is still the same, so caller should generally not have to update their code due to that.  However, the underlying btcjson package API has
changed significantly.  Since this package hides the vast majority of that from callers, it should not afffect them very much.  However, one area in particular to watch out for is that the old btcjson.Error is now btcjson.RPCError, so any callers doing any type assertions there will need to update.
The following is a summary of the changes:
- The underlying btcjson …
=> Update to make use of version 2 of btcjson.

wallet.go
https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list
getnewaddress get an optional account parameter.This parameter is missing on btcrpcclient, so I added it. It's still possible to add the address in default account using 'nil'.
=> Add account param on GetNewAddress

wallet.go
Before, calling ListSinceBlock(Async) would create an empty string
from the nil block hash.
=> Make listsinceblock block hash optional.

rawtransactions.go
**This pull request depends on btcsuite/btcd#487**
This pull request modifies the `SearchRawTransactions` and `SearchRawTransactionsVerbose` functions to work properly with the latest `searchrawtransactions` API in btcd.
In particular, this involves changing the return value from `[]*btcjson.TxRawResult` to `[]*btcjson.SearchRawTransactionResult` and adding the additional optional parameter which specifies whether or not to include information about the previous outputs.
=> Update SearchRawTransaction calls for latest API.

rawtransactions.go
I created this patch to match [btcd pull request 516](https://github.com/btcsuite/btcd/pull/516) at request of @dajohi
It builds cleanly.  I'm not sure how to test beyond that though.   I did build/run the btcdwebsockets example, fwiw.
=> add filteraddrs param to searchrawtransactions

infrastructure.go
Don't log "Established connection" message on New() when
DisableConnectOnNew is set and no connection was actually established.
Do log that same message when Connect() successfully connects.
=> Fix "Established connection" log message.

.travis.yml
This updates the Go versions using when running the TravisCI integration tests to reflect the latest supported Go versions.
Also, the vet tool moved into the Go source tree as of Go 1.5.  Its previous location in the `x/tools` repo was deprecated at that time and has now been removed.
Finally, old tool path is no longer needed, so it has been removed.
=> TravisCI: Update to latest configurations.

notify.go
This makes `go vet` happy by manually copying the notification state fields during the deep copy instead of copying the entire struct which contains an embedded mutex.
=> Manually copy relevant fields in ntfn state copy.

infrastructure.go, notify.go
This refactors the notification state mutex out of the state itself to the client.  This is being done since the code makes a copy of the notification state and accesses that copy immutably, and therefore there is no need for it to have its own mutex.
=> Refactor ntfnstate mutex.

chain.go
This modifies the return value of the `GetBlock` and `GetBlockAsync` functions to a raw `*wire.MsgBlock` instead of `*btcutil.Block`.
This is being done because a `btcutil.Block` assumes there is a height associated with the block and the block height is not part of a raw serialized block as returned by the underlying non-verbose RPC API
`getblock` call and thus is not available to populate a `btcutil.Block` correctly.
A raw `wire.Block` correctly matches what the underlying RPC call is actually returning and thus avoids the confusion that could occur.
Closes #86.
=> Return wire.MsgBlock from GetBlock(Async).

chain.go
This changes the GetBlockVersion API to not send a third parameter.
The third parameter is a boolean that expands the transaction data
structures as well.  However, Bitcore Core does not recognize this
feature.
GetBlockVerbose now only takes a hash value.
Users of the GetBlockVerbose(hash, true) must now use
GetBlockVerboseTx(hash).
Fixes #90
=> Fix GetBlockVerbose API.

chain.go
This commit adds `btcrpcclient` support for the recently implemented `getblockchaininfo` RPC.
The PR btcsuite/btcd#775 is dependent on this PR.
=> add support for getblockchaininfo

mining.go, net.go, notify.go, wallet.go
This simplifies the code based on the recommendations of the [gosimple](https://github.com/dominikh/go-simple) lint tool.
=> Simplify code per gosimple linter.

goclean.sh
This modifies the `goclean.sh` script to include the `gosimple` lint tool to the `gometalinter` configuration.
=> build: Add gosimple linter to goclean.sh.

notify.go
This removes all unnecessary typecast conversions as found by the [unconvert](https://github.com/mdempsky/unconvert) linter.
=> Remove unnecessary convs found by unconvert.

goclean.sh
This modifies the `goclean.sh` script to include the `unconvert` lint tool in the `gometalinter` configuration.
=> build: Add unconvert linter to goclean.sh.

LICENSE, extensions.go
This pull request is a backport of the `version` JSON-RPC API command from dcrd. It permits the JSON-RPC API to have its own semantic versioning scheme separate from the underlying software. The initial version is 1.0.0.
=> Add `version` command to JSON-RPC API for API versioning

chain.go, notify.go
This PR allows `btcrpcclient` to take advantage of the new `loadtxfilter` and `rescanblocks` commands and `relevanttxaccepted` notification in `btcd`. It also creates two new notification listeners, `OnFilteredBlockConnected` and `OnFilteredBlockDisconnected` to allow clients to access the newly-available data in the new `filteredblockconnected` and `filteredblockdisconnected` notifications; these listeners should be used with the combination of `loadtxfilter` and `notifynewblocks`. The old `OnBlockConnected` and `OnBlockDisconnected` listeners have been left in for backward compatibility for the `blockconnected` and `blockdisconnected` notifications..
=> Backport `loadtxfilter` and `rescanblocks` JSON-RPC command from dcrd

examples/btcdwebsockets/main.go
The old notifications are now deprecated, so the examples shouldn't use them.
=> Update ws example to use new filtered blocks ntfns.
